name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      # Todo se ejecuta dentro de la carpeta healthtrack/
      run:
        working-directory: healthtrack

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/healthtrack/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build & Unit Tests
        run: mvn --batch-mode --errors --fail-at-end test

      - name: Functional tests (bypass)
        run: echo "🔶 Bypass de pruebas funcionales — no se ejecutan en este pipeline."

      - name: Report summary
        if: ${{ always() }}
        run: |
          echo "✅ Build and unit tests: ${{ job.status }} • Functional tests: bypassed"